apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-test-app
  labels:
    app: git-test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: git-test-app
  template:
    metadata:
      labels:
        app: git-test-app
    spec:
      containers:
        - name: git-test-app
          image: demoAcrParkjh.azurecr.io/git-test-app:latest
          ports:
            - containerPort: 8000
